#!/usr/bin/bash

echo "Podaj ilosc uzytkownikow"
read x

for ((i=1; i<=x; i++))
do
sudo useradd  "user$i"
sudo passwd "user$i" "password$i"

echo "user$i" o hasle "password$i"  zostal utworzony.
done

y=$(($x/2))
sudo groupadd "studenci_informatyki"
sudo groupadd "studenci_etyki"

for((i=1; i<=(x/2); i++))
do
#sudo groupadd "studenci_informatyki"
sudo usermod -aG "studenci_informatyki" "user$i"
done
echo Uzytkownikow 1-$y przypisano do grupy Informatyka


for ((i=(y+1); i<=x; i++))
do
#sudo groupadd "studenci_etyki"
sudo usermod -aG "studenci_etyki" "user$i"
done
echo Uzytkownikow $y - $x przypisano do grupy Etyka

echo "Czy chciabys wyswietlic informacje o kontach? t/n"
read qa

ok="t"
no="n"

if [[ "$qa" == "$ok" ]]; then
echo "Lista uzytkownikow"
cut -d: -f1 /etc/passwd
echo ""

echo "informacje o uzytkownikach"
for ((j=1;j<=x;j++))
do
id user$j
done
echo ""

echo "Lista grup"
cut -d: -f1 /etc/group
echo ""

echo "informacje o grupach"
getent group studenci_informatyki
getent group studenci_etyki
elif [[ "$qa" == "$no" ]]; then
echo "wybrales nie"
else

echo "Nie udala sie"
fi
